### ISSUE TITLE
conda-build broken: missing libiconv.so.2

### ISSUE THREAD

**Issue by trey-stafford** [conda-forge/conda-build-feedstock#109]
Issue:
conda-build >=3.0.31 is broken.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
_libgcc_mutex             0.1                        main
asn1crypto                0.24.0                py37_1003    conda-forge
beautifulsoup4            4.8.0                    py37_0    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.7.10                   py37_0    conda-forge
conda-build               3.17.8                   py37_1    conda-forge
conda-package-handling    1.4.1                    py37_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 he1b5a44_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
libarchive                3.3.3             hb44662c_1005    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
liblief                   0.9.0                hf8a498c_1    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libxml2                   2.9.9                h8cf2a2b_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
soupsieve                 1.9.2                    py37_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : build
    active env location : /opt/conda/envs/build
            shell level : 2
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-55-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

Attempting to `conda build` an environment with conda >=3.17 is broken.

with `conda-build` v3.17.8:
```
(build) root@68706a69c17d:/seaice# BUILD_NUMBER=0 conda build recipe/ --python 3.5
Traceback (most recent call last):
  File "/opt/conda/envs/build/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import root_dir, root_writable
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda_build/conda_interface.py", line 37, in <module>
    from conda.exports import display_actions, execute_actions, execute_plan, install_actions
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda/plan.py", line 25, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda_package_handling/api.py", line 12, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2, libarchive_enabled
  File "/opt/conda/envs/build/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 11, in <module>
    import libarchive
  File "/opt/conda/envs/build/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/opt/conda/envs/build/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/opt/conda/envs/build/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/opt/conda/envs/build/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/opt/conda/envs/build/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
```

**Comment by mbargull** [comment]
`conda-forge::libarchive>=3.4.3` doesn't link to `libiconv` on Linux anymore, so we can close this old issue.
