### ISSUE TITLE
Issue with CI builds of feedstock post conda-build upgrade

### ISSUE THREAD

**Issue by chambbj** [conda-forge/conda-build-feedstock#39]
Per @jakirkham advice (https://github.com/conda-forge/pdal-feedstock/issues/1#issuecomment-382759759), opening this issue as the `pdal-feedstock` which had been passing both Linux [1] and macOS [2] in `conda-forge/staged-recipes` prior to the upgrade from `conda-build` 2 to 3, now fail both Linux and macOS as a feedstock, as shown below.

https://circleci.com/gh/conda-forge/pdal-feedstock/6

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2105, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1515, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 917, in bundle_conda
    files = post_process_files(metadata, initial_files)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 780, in post_process_files
    post_build(m, new_files, build_python=python)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 642, in post_build
    osx_is_app=osx_is_app)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/post.py", line 54, in fix_shebang
    with io.open(path, encoding=locale.getpreferredencoding(), mode='r+') as fi:
PermissionError: [Errno 13] Permission denied: '/home/conda/feedstock_root/build_artifacts/pdal_1524146590889/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/pdal-config'
```

https://travis-ci.org/conda-forge/pdal-feedstock/builds/368307455

```
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 129, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 119, in main
    upload(cli, fname, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 66, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmphe4j3uvo/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/pdal-1.7.1-hf626a3b_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
```

[1] https://circleci.com/gh/conda-forge/staged-recipes/25828<br>
[2] https://travis-ci.org/conda-forge/staged-recipes/builds/365092079

**Comment by jakirkham** [comment]
Sorry, I meant [here]( https://github.com/conda/conda-build/issues ).

**Comment by chambbj** [comment]
Oh, thanks. Relocating...

**Comment by chambbj** [comment]
Now being tracked at https://github.com/conda/conda-build/issues/2824
